//go:build ignore

package main

import (
	"fmt"
	"io/ioutil"
	"os"
	"path/filepath"
	"text/template"
)

const modelTemplate = `// Code generated by go generate. DO NOT EDIT.

package langid

// Embedded model data
var (
	// nb_ptc.bin - Probability table (7480×97 matrix)
	embeddedNbPtc = []byte{
		{{range .NbPtc}}{{.}},{{end}}
	}

	// nb_pc.bin - Prior probabilities (97 vector)
	embeddedNbPc = []byte{
		{{range .NbPc}}{{.}},{{end}}
	}

	// nb_classes.json - Language codes (97 codes)
	embeddedNbClasses = []byte{
		{{range .NbClasses}}{{.}},{{end}}
	}

	// tk_nextmove.bin - Tokenizer state transitions (2,334,208 elements)
	embeddedTkNextmove = []byte{
		{{range .TkNextmove}}{{.}},{{end}}
	}

	// tk_output.bin - Tokenizer output mappings (8,656 entries)
	embeddedTkOutput = []byte{
		{{range .TkOutput}}{{.}},{{end}}
	}
)
`

type ModelData struct {
	NbPtc      []byte
	NbPc       []byte
	NbClasses  []byte
	TkNextmove []byte
	TkOutput   []byte
}

func main() {
	dataDir := "data"
	if len(os.Args) > 1 {
		dataDir = os.Args[1]
	}

	// Read all model files
	modelData := ModelData{}

	// Read nb_ptc.bin
	nbPtcData, err := ioutil.ReadFile(filepath.Join(dataDir, "nb_ptc.bin"))
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error reading nb_ptc.bin: %v\n", err)
		os.Exit(1)
	}
	modelData.NbPtc = nbPtcData

	// Read nb_pc.bin
	nbPcData, err := ioutil.ReadFile(filepath.Join(dataDir, "nb_pc.bin"))
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error reading nb_pc.bin: %v\n", err)
		os.Exit(1)
	}
	modelData.NbPc = nbPcData

	// Read nb_classes.json
	nbClassesData, err := ioutil.ReadFile(filepath.Join(dataDir, "nb_classes.json"))
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error reading nb_classes.json: %v\n", err)
		os.Exit(1)
	}
	modelData.NbClasses = nbClassesData

	// Read tk_nextmove.bin
	tkNextmoveData, err := ioutil.ReadFile(filepath.Join(dataDir, "tk_nextmove.bin"))
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error reading tk_nextmove.bin: %v\n", err)
		os.Exit(1)
	}
	modelData.TkNextmove = tkNextmoveData

	// Read tk_output.bin
	tkOutputData, err := ioutil.ReadFile(filepath.Join(dataDir, "tk_output.bin"))
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error reading tk_output.bin: %v\n", err)
		os.Exit(1)
	}
	modelData.TkOutput = tkOutputData

	// Create template
	tmpl, err := template.New("model").Parse(modelTemplate)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error parsing template: %v\n", err)
		os.Exit(1)
	}

	// Execute template
	outputFile := "langid/embedded_model.gen.go"
	file, err := os.Create(outputFile)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error creating output file: %v\n", err)
		os.Exit(1)
	}
	defer file.Close()

	err = tmpl.Execute(file, modelData)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error executing template: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated embedded model file: %s\n", outputFile)
	fmt.Printf("Model sizes:\n")
	fmt.Printf("  nb_ptc.bin: %d bytes\n", len(modelData.NbPtc))
	fmt.Printf("  nb_pc.bin: %d bytes\n", len(modelData.NbPc))
	fmt.Printf("  nb_classes.json: %d bytes\n", len(modelData.NbClasses))
	fmt.Printf("  tk_nextmove.bin: %d bytes\n", len(modelData.TkNextmove))
	fmt.Printf("  tk_output.bin: %d bytes\n", len(modelData.TkOutput))
}
